---

- name: restart patroni-watchdog
  systemd:
    name: patroni-watchdog
    state: restarted
    daemon_reload: yes
    enabled: yes
  notify:
    - restart watchdog

- name: restart watchdog
  systemd:
    name: watchdog
    state: restarted
    enabled: yes
  retries: 5
  delay: 5
  register: result
  until: result.rc == 0

- name: restart patroni
  systemd:
    name: patroni.service
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: restart haproxy
  systemd:
    name: haproxy.service
    state: restarted
    daemon_reload: yes
    enabled: yes
